services:
  ollama:
    container_name: ollama
    build:
      context: _docker/ollama
      dockerfile: Dockerfile
    volumes:
      - ollama_storage:/root/.ollama
    ports:
      - "11434:11434"
    restart: always
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]

  bot:
    build: _docker/python
    container_name: bot
    depends_on:
      - ollama
    restart: always
    env_file:
      - .env
    deploy:
      resources:
        limits:
          memory: 2G


volumes:
  ollama_storage:

