services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    volumes:
      - ollama_storage:/root/.ollama
    ports:
      - "11434:11434"
    restart: always

  postgres:
    image: postgres:15-alpine
    ports:
      - '${PG_PORT}:5432'
    container_name: 'postgres'
    working_dir: '/app'
    restart: unless-stopped
    environment:
      POSTGRES_DB: '${PG_DB}'
      POSTGRES_USER: '${PG_USER}'
      POSTGRES_PASSWORD: '${PG_PASSWORD}'
    volumes:
      - postgresql:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          cpus: '1.5'
          memory: '1G'
        reservations:
          memory: '256M'

volumes:
  postgresql:
  ollama_storage:

